"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { format } from "date-fns";
import { Sparkles } from "lucide-react";
import type { Task, StaffUser, Patient } from "@prisma/client";
import { TaskStatus } from "@prisma/client";
import { Badge } from "@/components/ui/Badge";
import { Select } from "@/components/ui/Select";
import { updateTaskStatusAction } from "@/lib/actions/tasks";

type TaskRow = Task & { assignedTo: StaffUser | null; patient: Patient };

const STATUS_TONE = { PENDING: "amber", IN_PROGRESS: "blue", COMPLETED: "green" } as const;
const FILTERS = ["ALL", ...Object.values(TaskStatus)] as const;

export function TaskQueueClient({ tasks }: { tasks: TaskRow[] }) {
  const [filter, setFilter] = useState<(typeof FILTERS)[number]>("ALL");
  const [pendingIds, setPendingIds] = useState<Set<string>>(new Set());

  const visible = useMemo(
    () => (filter === "ALL" ? tasks : tasks.filter((t) => t.status === filter)),
    [tasks, filter]
  );

  async function onStatusChange(taskId: string, patientId: string, status: TaskStatus) {
    setPendingIds((prev) => new Set(prev).add(taskId));
    try {
      await updateTaskStatusAction(taskId, patientId, status);
    } finally {
      setPendingIds((prev) => {
        const next = new Set(prev);
        next.delete(taskId);
        return next;
      });
    }
  }

  return (
    <div className="p-6">
      <div className="mb-4 flex items-center justify-between">
        <h1 className="text-xl font-semibold text-slate-900">Task Queue</h1>
        <div className="flex gap-1.5">
          {FILTERS.map((f) => (
            <button
              key={f}
              onClick={() => setFilter(f)}
              className={`rounded-full border px-3 py-1 text-xs font-medium ${
                filter === f
                  ? "border-blue-300 bg-blue-50 text-blue-700"
                  : "border-slate-200 text-slate-500 hover:border-slate-300"
              }`}
            >
              {f === "ALL" ? "All" : f.replace("_", " ")}
            </button>
          ))}
        </div>
      </div>

      {visible.length === 0 ? (
        <p className="py-16 text-center text-sm text-slate-400">No tasks match this filter.</p>
      ) : (
        <div className="flex flex-col gap-2">
          {visible.map((t) => (
            <div
              key={t.id}
              className="flex items-center justify-between gap-4 rounded-xl border border-slate-200 bg-white p-4"
            >
              <div className="min-w-0">
                <p className="truncate text-sm font-medium text-slate-900" title={t.description}>
                  {t.description}
                  {t.isAutoGenerated && (
                    <Badge tone="blue">
                      <Sparkles size={9} className="mr-1 inline" />
                      Auto
                    </Badge>
                  )}
                </p>
                <p className="text-xs text-slate-500">
                  <Link href={`/dashboard/patients/${t.patientId}`} className="hover:underline">
                    {t.patient.firstName} {t.patient.lastName}
                  </Link>{" "}
                  · {t.assignedTo ? `Assigned to ${t.assignedTo.name}` : "Unassigned"} ·{" "}
                  {format(t.createdAt, "MMM d, yyyy")}
                </p>
              </div>
              <div className="flex shrink-0 items-center gap-2">
                <Select
                  id={`queue-status-${t.id}`}
                  value={t.status}
                  disabled={pendingIds.has(t.id)}
                  onChange={(e) => onStatusChange(t.id, t.patientId, e.target.value as TaskStatus)}
                  className="w-36 text-xs"
                >
                  {Object.values(TaskStatus).map((s) => (
                    <option key={s} value={s}>
                      {s.replace("_", " ")}
                    </option>
                  ))}
                </Select>
                <Badge tone={STATUS_TONE[t.status]}>{t.status.replace("_", " ")}</Badge>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
