import { prisma } from "@/lib/prisma";
import { TaskStatus } from "@prisma/client";

export function getTasksForPatient(patientId: string) {
  return prisma.task.findMany({
    where: { patientId },
    orderBy: { createdAt: "desc" },
    include: { assignedTo: true },
  });
}

export function getAllTasks() {
  return prisma.task.findMany({
    orderBy: { createdAt: "desc" },
    include: { assignedTo: true, patient: true },
  });
}

export interface AutoTaskInput {
  patientId: string;
  noteId: string;
  description: string;
  assignedToId?: string;
}

export function createAutoTasks(tasks: AutoTaskInput[]) {
  return prisma.task.createMany({
    data: tasks.map((t) => ({
      patientId: t.patientId,
      noteId: t.noteId,
      description: t.description,
      assignedToId: t.assignedToId,
      isAutoGenerated: true,
    })),
  });
}

export function updateTaskStatus(id: string, status: TaskStatus) {
  return prisma.task.update({ where: { id }, data: { status } });
}
