"use client";

import { useState } from "react";
import { format } from "date-fns";
import { ListChecks, Sparkles } from "lucide-react";
import type { Task, StaffUser } from "@prisma/client";
import { TaskStatus } from "@prisma/client";
import { Card, CardTitle } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { Select } from "@/components/ui/Select";
import { EmptyState } from "@/components/chart/UnifiedChartView";
import { updateTaskStatusAction } from "@/lib/actions/tasks";

type TaskWithAssignee = Task & { assignedTo: StaffUser | null };

interface TasksSectionProps {
  patientId: string;
  tasks: TaskWithAssignee[];
  staff: StaffUser[];
}

const STATUS_TONE = { PENDING: "amber", IN_PROGRESS: "blue", COMPLETED: "green" } as const;

export function TasksSection({ patientId, tasks }: TasksSectionProps) {
  const [pendingIds, setPendingIds] = useState<Set<string>>(new Set());

  async function onStatusChange(taskId: string, status: TaskStatus) {
    setPendingIds((prev) => new Set(prev).add(taskId));
    try {
      await updateTaskStatusAction(taskId, patientId, status);
    } finally {
      setPendingIds((prev) => {
        const next = new Set(prev);
        next.delete(taskId);
        return next;
      });
    }
  }

  return (
    <Card>
      <CardTitle className="mb-3 flex items-center gap-1.5">
        <ListChecks size={14} /> Task Queue
      </CardTitle>

      {tasks.length === 0 ? (
        <EmptyState label="No tasks for this patient." />
      ) : (
        <div className="flex flex-col gap-2">
          {tasks.map((t) => (
            <div key={t.id} className="flex items-center justify-between gap-3 rounded-lg bg-slate-50 px-3 py-2 text-sm">
              <div className="min-w-0">
                <p className="truncate font-medium text-slate-900" title={t.description}>
                  {t.description}
                  {t.isAutoGenerated && (
                    <Badge tone="blue">
                      <Sparkles size={9} className="mr-1 inline" />
                      Auto
                    </Badge>
                  )}
                </p>
                <p className="text-xs text-slate-500">
                  {t.assignedTo ? `Assigned to ${t.assignedTo.name}` : "Unassigned"} ·{" "}
                  {format(t.createdAt, "MMM d, yyyy")}
                </p>
              </div>
              <Select
                id={`task-status-${t.id}`}
                value={t.status}
                disabled={pendingIds.has(t.id)}
                onChange={(e) => onStatusChange(t.id, e.target.value as TaskStatus)}
                className="w-32 text-xs"
              >
                {Object.values(TaskStatus).map((s) => (
                  <option key={s} value={s}>
                    {s.replace("_", " ")}
                  </option>
                ))}
              </Select>
              <Badge tone={STATUS_TONE[t.status]}>{t.status.replace("_", " ")}</Badge>
            </div>
          ))}
        </div>
      )}
    </Card>
  );
}
